### ISSUE TITLE
Cannot use partial message view when using JSON serialization

### ISSUE THREAD

**Issue by agross** [jbogard/NServiceBus.MessageRouting#11]
I was trying to get the sample to run while using `configuration.UseSerialization<NewtonsoftSerializer>();`. As long as the sample runs with the default XML serializer everything works as expected.

After enabling JSON serialization (with default settings as above), the "partial view of the data" feature of the routing slip unfortunately no longer works: NSB includes the fully-qualified type name of `SequentialProcess` in the message header (`NServiceBus.EnclosedMessageTypes`), but the `StepA` host does not have access to the shared messages assembly and therefore cannot deserialize the type from the transport:

```
2019-03-10 13:31:54.344 WARN  NServiceBus.DeserializeLogicalMessagesConnector Could not determine message type from message header 'NServiceBus.MessageRouting.RoutingSlips.Samples.Messages.SequentialProcess, NServiceBus.MessageRouting.RoutingSlips.Samples.Messages, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'. MessageId: cb828782-7673-4ad5-9487-aa0c00ce2cb6
2019-03-10 13:31:54.347 ERROR NServiceBus.RecoverabilityExecutor Moving message 'cb828782-7673-4ad5-9487-aa0c00ce2cb6' to the error queue 'error' because processing failed due to an exception:
NServiceBus.MessageDeserializationException: An error occurred while attempting to extract logical messages from incoming physical message cb828782-7673-4ad5-9487-aa0c00ce2cb6 ---> System.Exception: Could not find metadata for 'Newtonsoft.Json.Linq.JObject'.
Ensure the following:
1. 'Newtonsoft.Json.Linq.JObject' is included in initial scanning.
2. 'Newtonsoft.Json.Linq.JObject' implements either 'IMessage', 'IEvent' or 'ICommand' or alternatively, if you don't want to implement an interface, you can use 'Unobtrusive Mode'.
```

I needed to remove the `SequentialProcess` class from `StepA` and reference the shared messages assembly to make the sample work with JSON serialization.

**Comment by agross** [comment]
Another possible solution that allows keeping the partial message view (i.e. not having to use the shared messages assembly) is to replace the assembly qualified name with the type name on the sender side as shown [here](https://docs.particular.net/samples/consumer-driven-contracts/#full-names-instead-of-fully-qualified-assembly-names).

**Comment by jbogard** [comment]
I wonder if this isn't a problem with the sample as much it is a quirk of the serialization. If someone wants to do CDC with JSON, they'll run into this, right?

In practice, I'd almost certainly just share the message assembly. The sample is to show that it's not necessary - for example if someone has an older version of the message, it forwards the original message from endpoint to endpoint, not the re-serialized message.

**Comment by agross** [comment]
It's definitely related to the serialization format. I was already trying to get something similar to run with my NSB solution twice during the last couple of months and always failed. So this issue is more of an attempt to document the quirk than to ask for a solution.
