### ISSUE TITLE
Newtonsoft Json.Net Update

### ISSUE THREAD

**Issue by PhilSandersonK3** [jbogard/NServiceBus.MessageRouting#8]
Thanks - this library is very useful.  However, trying to update alongside the newer .NET Core libraries is difficult as they have newer versions of Json.Net, and NServiceBus.MessageRouting insists on version < 11 on this. 

Have temporarily made my own nuget package to get around this, but it would be handy to have this as part of the official repo if it's not too much trouble?

**Comment by jbogard** [comment]
PR?

**Comment by PhilSandersonK3** [comment]
Added for your review, thanks!
